import { ICountry } from "./interfaces/country-interface";
import { ICurrency } from "./interfaces/currency-interface";


export const CURRENCIES: ICurrency[] = [
  { iso4217: 'AED', base: 100 },
    { iso4217: 'ARS', base: 100 },
    { iso4217: 'AUD', base: 100 },
    { iso4217: 'BHD', base: 1000 },
    { iso4217: 'BRL', base: 100 },
    { iso4217: 'CHF', base: 100 },
    { iso4217: 'CNY', base: 100 },
    { iso4217: 'COP', base: 100 },
    { iso4217: 'EGP', base: 100 },
    { iso4217: 'EUR', base: 100 },
    { iso4217: 'GBP', base: 100 },
    { iso4217: 'HKD', base: 100 },
    { iso4217: 'KWD', base: 1000 },
    { iso4217: 'MXN', base: 100 },
    { iso4217: 'NOK', base: 100 },
    { iso4217: 'NZD', base: 100 },
    { iso4217: 'PLN', base: 100 },
    { iso4217: 'QAR', base: 100 },
    { iso4217: 'SEK', base: 100 },
    { iso4217: 'SGD', base: 100 },
    { iso4217: 'SAR', base: 100 },
    { iso4217: 'USD', base: 100 },
  ];

  export const COUNTRIES: ICountry[] =[
    {name: 'Germany' , alpha2Code:'DE'},
    {name: 'United Kingdom' , alpha2Code:'GB'},
    {name: 'United States' , alpha2Code:'US'},
    {name: 'France' , alpha2Code:'FR'},
    {name: 'Italy' , alpha2Code:'IT'},
    {name: 'Spain' , alpha2Code:'ES'},
    {name: 'Netherlands' , alpha2Code:'NL'},
    {name: 'Belgium' , alpha2Code:'BE'},
    {name: 'Switzerland' , alpha2Code:'CH'},
    {name: 'Austria' , alpha2Code:'AT'},
    {name: 'Finland' , alpha2Code:'FI'},
    {name: 'Czech Republic' , alpha2Code:'CK'},
    {name: 'Estonia' , alpha2Code:'ES'},
    {name: 'Denmark' , alpha2Code:'DK'},
    {name: 'Poland' , alpha2Code:'PL'},
    {name: 'Portugal' , alpha2Code:'PT'},
    {name: 'Sweden' , alpha2Code:'SE'},
    {name: 'Norway' , alpha2Code:'NO'},
    {name: 'Hungary' , alpha2Code:'HU'},
    {name: 'Kuwait' , alpha2Code:'KW'},
    {name: 'Qatar' , alpha2Code:'DE'},
    {name: 'Bahrain' , alpha2Code:'BH'},
    {name: 'Newzealand' , alpha2Code:'AZ'},
    {name: 'Egypt' , alpha2Code:'EG'},
    {name: 'Brazil' , alpha2Code:'BR'},
    {name: 'Hongkong' , alpha2Code:'HK'},
    {name: 'Australia' , alpha2Code:'AU'},
    {name: 'United Arab Emirates' , alpha2Code:'AU'}
  ]